<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>ConnectedMining</AssemblyName>
    <Version>1.1.0</Version>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <ValheimDir Condition="'$(ValheimDir)' == ''">D:\SteamLibrary\steamapps\common\Valheim</ValheimDir>
    <BepInExDir Condition="'$(BepInExDir)' == ''">D:\ValheimModTools\BepInExPack-5.4.2351\BepInExPack_Valheim\BepInEx</BepInExDir>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="src\*.cs" />
    <Reference Include="BepInEx"><HintPath>$(BepInExDir)\core\BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(BepInExDir)\core\0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="assembly_valheim"><HintPath>$(ValheimDir)\valheim_Data\Managed\assembly_valheim.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="assembly_utils"><HintPath>$(ValheimDir)\valheim_Data\Managed\assembly_utils.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(ValheimDir)\valheim_Data\Managed\UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(ValheimDir)\valheim_Data\Managed\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.PhysicsModule"><HintPath>$(ValheimDir)\valheim_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TerrainPhysicsModule"><HintPath>$(ValheimDir)\valheim_Data\Managed\UnityEngine.TerrainPhysicsModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="System.Net.Http"><HintPath>$(ValheimDir)\valheim_Data\Managed\System.Net.Http.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="System.IO.Compression"><HintPath>$(ValheimDir)\valheim_Data\Managed\System.IO.Compression.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
